backend:
  name: git-gateway
  branch: main

media_folder: public/media/uploads
public_folder: /media/uploads

site_url: https://hackatontips.netlify.app/
display_url: https://hackatontips.netlify.app/

collections:
  - name: "projects"
    label: "Prosjekter"
    extensions: "json"
    format: json
    files: 
      - file: "public/json/projects.json"
        label: "Prosjekter"
        name: "projects"
        fields:
          - name: 'prosjekt'
            label: 'Prosjekt'
            label-singular: 'Prosjekt'
            widget: 'list'
            summary: '{{fields.title}}'
            fields:
              - name: 'title'
                label: 'Navn'
                widget: 'string'
                required: true
              - name: 'description'
                label: 'Beskrivelse'
                widget: 'text'
                required: true
              - name: 'min'
                label: 'Deltagere (min)'
                widget: 'number'
                required: true
              - name: 'max'
                label: 'Deltagere (maks)'
                widget: 'number'
              - name: 'skills'
                label: 'Ferdigheter'
                widget: 'object'
                fields:
                  - name: 'frontend'
                    label: 'Frontend'
                    widget: 'boolean'
                  - name: 'backend'
                    label: 'Backend'
                    widget: 'boolean'
                  - name: 'game'
                    label: 'Games'
                    widget: 'boolean'
              - name: 'tags'
                label: 'Tags'
                widget: 'list'
                allow_add: true
                allow_delete: true
                fields:
                  - name: 'tag'
                    label: 'Tag'
                    widget: 'string'
